//! `spec/PERFORMANCE.md` §12.1's byte-identical levers, held to "did not move".
//!
//! Each lever is a `Tunables::accel_*` flag, off in `Tunables::DEFAULT`, whose
//! argument for byte identity is written beside its code. An argument is not a
//! result, so this file checks the result two ways:
//!
//! 1. **The spec vectors.** Every encode, decode and capped-decode vector in
//!    `spec/test-vectors/` must reproduce with each lever on alone and with all
//!    of them on together. These are the bytes every language is held to; no
//!    binding exposes `Tunables`, so the Rust core is where a lever lives and
//!    where it is checked, and a lever that later becomes the default is checked
//!    in every language by these same vectors.
//! 2. **A differential sweep.** The vectors pin the shipped `Tunables`, and
//!    several levers only do anything off them: the table lever with a tiered
//!    layout (`LAYOUT_C`, two bit widths in one job), the early exit with
//!    refinement on, the fused pass with alpha. So every lever is also compared
//!    against the shipped path under a set of non-default `Tunables` that reach
//!    those code paths, over deterministic images (opaque and translucent, 1-px
//!    strips to 64×48, all five gamuts, every tier the size can afford in a
//!    debug build).
//!
//! The inputs are generated by a fixed LCG rather than drawn by proptest: a
//! failure here names an exact case and reproduces on every run.

use chromahash::{ChromaHash, Companding, Gamut, LAYOUT_C, Tunables};
use serde_json::Value;

const ENCODE_VECTORS: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../spec/test-vectors/integration-encode.json"
));
const DECODE_VECTORS: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../spec/test-vectors/integration-decode.json"
));
const DECODE_CAPPED_VECTORS: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../spec/test-vectors/integration-decode-capped.json"
));

type Lever = (&'static str, fn(&mut Tunables));

/// Every §12.1 lever, by the name its flag carries.
const LEVERS: [Lever; 7] = [
    ("accel_quant_table", |t| t.accel_quant_table = true),
    ("accel_dct_lanes", |t| t.accel_dct_lanes = true),
    ("accel_gamma_lut_cache", |t| t.accel_gamma_lut_cache = true),
    ("accel_flat_cos", |t| t.accel_flat_cos = true),
    ("accel_sse_early_exit", |t| t.accel_sse_early_exit = true),
    ("accel_fused_pixels", |t| t.accel_fused_pixels = true),
    ("accel_word_bitpack", |t| t.accel_word_bitpack = true),
];

/// Each lever alone on top of `base`, then all of them together.
fn arms(base: Tunables) -> Vec<(String, Tunables)> {
    let mut out: Vec<(String, Tunables)> = LEVERS
        .iter()
        .map(|(name, set)| {
            let mut t = base;
            set(&mut t);
            ((*name).to_string(), t)
        })
        .collect();
    let mut all = base;
    for (_, set) in LEVERS {
        set(&mut all);
    }
    out.push(("all levers".to_string(), all));
    out
}

#[test]
fn every_lever_is_off_in_the_shipped_defaults() {
    // The flags exist so each lever can be timed against the shipped path, and
    // they are all off so the shipped path *is* that reference. Turning one on
    // by default is a separate, deliberate change: the tests below are what
    // would let it land in a patch release.
    let d = std::hint::black_box(Tunables::DEFAULT);
    for (name, set) in LEVERS {
        let mut t = d;
        set(&mut t);
        assert_ne!(
            t, d,
            "{name} does not set anything the default leaves unset"
        );
    }
    assert!(!d.accel_quant_table);
    assert!(!d.accel_dct_lanes);
    assert!(!d.accel_gamma_lut_cache);
    assert!(!d.accel_flat_cos);
    assert!(!d.accel_sse_early_exit);
    assert!(!d.accel_fused_pixels);
    assert!(!d.accel_word_bitpack);
}

fn gamut_from_str(s: &str) -> Gamut {
    match s {
        "sRGB" => Gamut::Srgb,
        "Display P3" => Gamut::DisplayP3,
        "Adobe RGB" => Gamut::AdobeRgb,
        "BT.2020" => Gamut::Bt2020,
        "ProPhoto RGB" => Gamut::ProPhotoRgb,
        other => panic!("unknown gamut in spec vector: {other:?}"),
    }
}

fn bytes(v: &Value) -> Vec<u8> {
    v.as_array()
        .expect("expected a JSON array of bytes")
        .iter()
        .map(|n| n.as_u64().expect("byte should be a number") as u8)
        .collect()
}

fn cases(json: &str) -> Vec<Value> {
    let v: Value = serde_json::from_str(json).expect("parse vectors");
    let a = v.as_array().expect("vectors should be an array").clone();
    assert!(!a.is_empty(), "no vectors found");
    a
}

#[test]
fn spec_encode_vectors_reproduce_under_every_lever() {
    for (arm, t) in arms(Tunables::DEFAULT) {
        for case in cases(ENCODE_VECTORS) {
            let name = case["name"].as_str().unwrap_or("<unnamed>");
            let input = &case["input"];
            let hash = ChromaHash::encode_tuned_quality(
                input["width"].as_u64().unwrap() as u32,
                input["height"].as_u64().unwrap() as u32,
                &bytes(&input["rgba"]),
                gamut_from_str(input["gamut"].as_str().unwrap()),
                &t,
                input["tier"].as_u64().unwrap() as u8,
            );
            assert_eq!(
                hash.as_bytes().to_vec(),
                bytes(&case["expected"]["hash"]),
                "{arm}: {name}: hash moved"
            );
        }
    }
}

#[test]
fn spec_decode_vectors_reproduce_under_every_lever() {
    for (arm, t) in arms(Tunables::DEFAULT) {
        for case in cases(DECODE_VECTORS) {
            let name = case["name"].as_str().unwrap_or("<unnamed>");
            let hash = ChromaHash::from_bytes(&bytes(&case["input"]["hash"])).unwrap();
            let (w, h, rgba) = hash.decode_tuned(&t);
            let e = &case["expected"];
            assert_eq!(w as u64, e["width"].as_u64().unwrap(), "{arm}: {name}");
            assert_eq!(h as u64, e["height"].as_u64().unwrap(), "{arm}: {name}");
            assert_eq!(rgba, bytes(&e["rgba"]), "{arm}: {name}: pixels moved");
        }
        for case in cases(DECODE_CAPPED_VECTORS) {
            let name = case["name"].as_str().unwrap_or("<unnamed>");
            let input = &case["input"];
            let hash = ChromaHash::from_bytes(&bytes(&input["hash"])).unwrap();
            let (w, h, rgba) = hash.decode_capped_tuned(
                input["max_width"].as_u64().unwrap() as u32,
                input["max_height"].as_u64().unwrap() as u32,
                &t,
            );
            let e = &case["expected"];
            assert_eq!(w as u64, e["width"].as_u64().unwrap(), "{arm}: {name}");
            assert_eq!(h as u64, e["height"].as_u64().unwrap(), "{arm}: {name}");
            assert_eq!(rgba, bytes(&e["rgba"]), "{arm}: {name}: pixels moved");
        }
    }
}

// ── The differential sweep ──────────────────────────────────────────────────

/// A deterministic image: `kind` 0 = noise, 1 = gradient, 2 = noise with a
/// translucent alpha ramp, 3 = gradient with fully transparent holes.
fn image(w: u32, h: u32, kind: u32, seed: u32) -> Vec<u8> {
    let mut s = seed.wrapping_mul(0x9e37_79b9) ^ 0x85eb_ca6b;
    let mut next = || {
        s = s.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
        (s >> 24) as u8
    };
    let (w, h) = (w as usize, h as usize);
    let mut rgba = vec![0u8; w * h * 4];
    for y in 0..h {
        for x in 0..w {
            let i = (y * w + x) * 4;
            let gx = if w > 1 { (x * 255 / (w - 1)) as u8 } else { 97 };
            let gy = if h > 1 {
                (y * 255 / (h - 1)) as u8
            } else {
                161
            };
            let (r, g, b) = match kind {
                1 | 3 => (gx, gy, 128),
                _ => (next(), next(), next()),
            };
            let a = match kind {
                2 => (((x + y) * 255) / (w + h)) as u8,
                3 if (x / 3 + y / 2) % 4 == 0 => 0,
                _ => 255,
            };
            rgba[i..i + 4].copy_from_slice(&[r, g, b, a]);
        }
    }
    rgba
}

/// Non-default `Tunables` that reach the paths the spec vectors cannot.
fn bases() -> Vec<(&'static str, Tunables)> {
    let d = Tunables::DEFAULT;
    vec![
        ("shipped", d),
        (
            // Two bit widths in one luma job at tiers >= 2: the case a table
            // keyed on the index alone would get wrong.
            "LAYOUT_C upper",
            Tunables {
                layout_upper: LAYOUT_C,
                ..d
            },
        ),
        (
            // The early exit's only caller, with every coordinate it scores.
            "refine",
            Tunables {
                refine_passes: 2,
                refine_delta: 2,
                refine_dc: true,
                refine_scale: true,
                ..d
            },
        ),
        (
            "refine on the render grid, weighted objective",
            Tunables {
                refine_passes: 1,
                refine_grid: 1,
                refine_obj: 3,
                refine_wl: 0.7,
                refine_wc: 1.3,
                ..d
            },
        ),
        (
            "alpha through the channel quantizer",
            Tunables {
                alpha_ac_fit: true,
                ..d
            },
        ),
        ("chroma from luma", Tunables { cfl_bits: 5, ..d }),
        (
            "shared chroma scale, interleaved payload",
            Tunables {
                b_scale_from_a: true,
                interleave: true,
                ..d
            },
        ),
        (
            "plain scale policy, deadzone, µ-law scale grid",
            Tunables {
                scale_fit: 1,
                ac_nearest: false,
                deadzone_l: 0.03,
                deadzone_c: 0.05,
                scale_mu: 4.0,
                ..d
            },
        ),
        (
            "other companding families, band gain",
            Tunables {
                compand_l: Companding::ALaw { a: 87.6 },
                compand_c: Companding::Power { gamma: 0.75 },
                band_gain_l: 1.4,
                band_gain_c: 0.8,
                ..d
            },
        ),
    ]
}

const GAMUTS: [Gamut; 5] = [
    Gamut::Srgb,
    Gamut::DisplayP3,
    Gamut::AdobeRgb,
    Gamut::Bt2020,
    Gamut::ProPhotoRgb,
];

/// Sizes, and the highest tier each is swept to.
///
/// Tier 2 is the top of the sweep on purpose. It is the first tier where
/// `LAYOUT_C` puts two bit widths in one luma job, so it reaches every path
/// tiers 3 and 4 do; what those add is cost, and it is the cost that does not
/// depend on the image — `scale_fit = 2` searches every scale code over every
/// selected coefficient, some 40 ms per tier-4 encode of a 1×1 image in a
/// release build, times eight arms, times every case. The spec vectors above
/// carry tiers 3 and 4 under every lever.
const SIZES: [((u32, u32), u8); 7] = [
    ((1, 1), 2),
    ((1, 23), 2),
    ((29, 1), 2),
    ((5, 3), 2),
    ((16, 9), 2),
    ((33, 17), 1),
    ((64, 48), 1),
];

#[test]
fn every_lever_matches_the_shipped_path_off_the_default_tunables() {
    let mut checked = 0usize;
    for (bi, (base_name, base)) in bases().into_iter().enumerate() {
        let refining = base.refine_passes > 0;
        for (si, &((w, h), max_tier)) in SIZES.iter().enumerate() {
            // Refinement is O(passes·K·W·H) per candidate: keep it to the
            // sizes and tiers where a debug build finishes it in seconds.
            if refining && w * h > 33 * 17 {
                continue;
            }
            let max_tier = if refining { max_tier.min(1) } else { max_tier };
            for kind in 0..4u32 {
                let rgba = image(w, h, kind, (bi * 131 + si * 17) as u32 + kind);
                let gamut = GAMUTS[(bi + si + kind as usize) % GAMUTS.len()];
                for tier in 0..=max_tier {
                    let reference =
                        ChromaHash::encode_tuned_quality(w, h, &rgba, gamut, &base, tier);
                    let out = GAMUTS[(si + tier as usize) % 3];
                    // A natural decode above tier 1 renders up to 256×256
                    // over hundreds of coefficients, per arm; the capped
                    // decode below reaches the same code at every tier.
                    let ref_px = (tier <= 1).then(|| reference.decode_to_tuned(out, &base));
                    let ref_cap = reference.decode_capped_tuned(7, 5, &base);
                    for (arm, t) in arms(base) {
                        let what = format!(
                            "{arm} over {base_name}: {w}x{h} kind {kind} {gamut:?} tier {tier}"
                        );
                        let hash = ChromaHash::encode_tuned_quality(w, h, &rgba, gamut, &t, tier);
                        assert_eq!(hash.as_bytes(), reference.as_bytes(), "{what}: hash moved");
                        if let Some(ref_px) = &ref_px {
                            assert_eq!(
                                &reference.decode_to_tuned(out, &t),
                                ref_px,
                                "{what}: decode to {out:?} moved"
                            );
                        }
                        assert_eq!(
                            reference.decode_capped_tuned(7, 5, &t),
                            ref_cap,
                            "{what}: capped decode moved"
                        );
                        checked += 1;
                    }
                }
            }
        }
    }
    // Guard against the sweep silently shrinking to nothing.
    assert!(checked > 2000, "only {checked} comparisons ran");
}
